"""learning paths

Revision ID: 3c0333513b97
Revises: b4a1c9d8e7f2
Create Date: 2026-05-04 12:35:22.408057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0333513b97'
down_revision: Union[str, None] = 'b4a1c9d8e7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_group_id'), 'learning_paths', ['group_id'], unique=False)
    op.create_table('learning_path_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_modules_path_id'), 'learning_path_modules', ['path_id'], unique=False)
    op.create_table('learning_path_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['learning_path_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'user_id', name='uq_module_user')
    )
    op.create_index(op.f('ix_learning_path_progress_module_id'), 'learning_path_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_learning_path_progress_path_id'), 'learning_path_progress', ['path_id'], unique=False)
    op.create_index(op.f('ix_learning_path_progress_user_id'), 'learning_path_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_path_progress_user_id'), table_name='learning_path_progress')
    op.drop_index(op.f('ix_learning_path_progress_path_id'), table_name='learning_path_progress')
    op.drop_index(op.f('ix_learning_path_progress_module_id'), table_name='learning_path_progress')
    op.drop_table('learning_path_progress')
    op.drop_index(op.f('ix_learning_path_modules_path_id'), table_name='learning_path_modules')
    op.drop_table('learning_path_modules')
    op.drop_index(op.f('ix_learning_paths_group_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
