"""restore user_events table and kpi_cache unique constraint

Migration c4875d29c5a5 was auto-generated by alembic --autogenerate.
It dropped user_events (not tracked in Base.metadata) and uq_kpi_cache.
This migration recreates both.

user_events is created as a plain PostgreSQL table without TimescaleDB so
that it works inside Alembic's transactional DDL context on fresh installs.

Revision ID: d1e2f3a4b5c6
Revises: 14a0f1adead3
Create Date: 2026-05-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "d1e2f3a4b5c6"
down_revision: Union[str, None] = "14a0f1adead3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Recreate user_events as a plain table.
    # c4875d29c5a5 dropped it because UserEvent is not a SQLAlchemy ORM model.
    op.create_table(
        "user_events",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("org_id", sa.String(36), nullable=True),
        sa.Column("event_type", sa.String(100), nullable=False),
        sa.Column("resource_type", sa.String(50), nullable=True),
        sa.Column("resource_id", sa.String(36), nullable=True),
        sa.Column("metadata", JSONB, nullable=True, server_default="{}"),
    )
    op.create_index("ix_user_events_time", "user_events", ["time"])
    op.create_index("ix_user_events_user_id", "user_events", ["user_id"])
    op.create_index("ix_user_events_org_id", "user_events", ["org_id"])
    op.create_index("ix_user_events_event_type", "user_events", ["event_type"])

    # Restore uq_kpi_cache dropped by c4875d29c5a5.
    # Required for _upsert_kpi's ON CONFLICT (scope_type, scope_id, metric_key, date).
    op.create_unique_constraint(
        "uq_kpi_cache",
        "kpi_cache",
        ["scope_type", "scope_id", "metric_key", "date"],
    )


def downgrade() -> None:
    op.drop_constraint("uq_kpi_cache", "kpi_cache", type_="unique")
    op.drop_index("ix_user_events_event_type", table_name="user_events")
    op.drop_index("ix_user_events_org_id", table_name="user_events")
    op.drop_index("ix_user_events_user_id", table_name="user_events")
    op.drop_index("ix_user_events_time", table_name="user_events")
    op.drop_table("user_events")
